/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module bad_case(i0, i1, i2, i3, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input i0;
  input i1;
  input i2;
  input i3;
  input [1:0] sel;
  output y;
  sky130_fd_sc_hd__mux4_2 _14_ (
    .A0(_00_),
    .A1(_02_),
    .A2(_01_),
    .A3(_03_),
    .S0(_05_),
    .S1(_04_),
    .X(_06_)
  );
  assign _03_ = i3;
  assign y = _06_;
  assign _05_ = sel[1];
  assign _04_ = sel[0];
  assign _01_ = i1;
  assign _02_ = i2;
  assign _00_ = i0;
endmodule
