/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module mux_generate(i0, i1, i2, i3, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input i0;
  input i1;
  input i2;
  input i3;
  wire [3:0] i_int;
  wire [31:0] k;
  input [1:0] sel;
  output y;
  sky130_fd_sc_hd__mux4_2 _16_ (
    .A0(_10_),
    .A1(_11_),
    .A2(_12_),
    .A3(_13_),
    .S0(_14_),
    .S1(_15_),
    .X(_08_)
  );
  \$_DLATCH_P_  _17_ (
    .D(_00_),
    .E(_01_),
    .Q(y)
  );
  assign i_int = { i3, i2, i1, i0 };
  assign k = 32'd4;
  assign _09_ = 1'h1;
  assign _14_ = sel[0];
  assign _15_ = sel[1];
  assign _10_ = i0;
  assign _11_ = i1;
  assign _12_ = i2;
  assign _13_ = i3;
  assign _00_ = _08_;
  assign _01_ = _09_;
endmodule
