/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module partial_case_assign(i0, i1, i2, sel, y, x);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input i0;
  input i1;
  input i2;
  input [1:0] sel;
  output x;
  output y;
  sky130_fd_sc_hd__nand2b_1 _18_ (
    .A_N(_09_),
    .B(_08_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__and3b_1 _19_ (
    .A_N(_09_),
    .B(_08_),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _20_ (
    .A(_09_),
    .B(_08_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a221o_1 _21_ (
    .A1(_05_),
    .A2(_09_),
    .B1(_03_),
    .B2(_07_),
    .C1(_06_),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _22_ (
    .A0(_04_),
    .A1(_05_),
    .S(_07_),
    .X(_01_)
  );
  \$_DLATCH_P_  _23_ (
    .D(_00_),
    .E(_11_),
    .Q(x)
  );
  assign _05_ = i2;
  assign y = _10_;
  assign _09_ = sel[1];
  assign _08_ = sel[0];
  assign _11_ = _02_;
  assign _04_ = i1;
  assign _00_ = _01_;
  assign _03_ = i0;
endmodule
